`timescale 1ns/1ps

module tensor_writer (
  input  logic clk,
  input  logic rst_n,
  input  logic start_i,
  input  logic [31:0] ext_addr_i,
  input  logic [31:0] byte_len_i,
  input  logic [15:0] spad_offset_i,
  output logic busy_o,
  output logic done_o,
  output logic error_o,
  output logic cross_4kb_o,

  output logic [31:0] m_axi_awaddr,
  output logic [7:0]  m_axi_awlen,
  output logic [2:0]  m_axi_awsize,
  output logic [1:0]  m_axi_awburst,
  output logic        m_axi_awvalid,
  input  logic        m_axi_awready,
  output logic [63:0] m_axi_wdata,
  output logic [7:0]  m_axi_wstrb,
  output logic        m_axi_wlast,
  output logic        m_axi_wvalid,
  input  logic        m_axi_wready,
  input  logic [1:0]  m_axi_bresp,
  input  logic        m_axi_bvalid,
  output logic        m_axi_bready,

  output logic        spad_req_o,
  output logic        spad_we_o,
  output logic [15:0] spad_addr_o,
  input  logic [31:0] spad_rdata_i,
  input  logic        spad_ready_i
);
  axi_write_dma u_axi_write_dma (
    .clk(clk),
    .rst_n(rst_n),
    .start_i(start_i),
    .addr_i(ext_addr_i),
    .byte_len_i(byte_len_i),
    .spad_offset_i(spad_offset_i),
    .busy_o(busy_o),
    .done_o(done_o),
    .error_o(error_o),
    .cross_4kb_o(cross_4kb_o),
    .m_axi_awaddr(m_axi_awaddr),
    .m_axi_awlen(m_axi_awlen),
    .m_axi_awsize(m_axi_awsize),
    .m_axi_awburst(m_axi_awburst),
    .m_axi_awvalid(m_axi_awvalid),
    .m_axi_awready(m_axi_awready),
    .m_axi_wdata(m_axi_wdata),
    .m_axi_wstrb(m_axi_wstrb),
    .m_axi_wlast(m_axi_wlast),
    .m_axi_wvalid(m_axi_wvalid),
    .m_axi_wready(m_axi_wready),
    .m_axi_bresp(m_axi_bresp),
    .m_axi_bvalid(m_axi_bvalid),
    .m_axi_bready(m_axi_bready),
    .spad_req_o(spad_req_o),
    .spad_we_o(spad_we_o),
    .spad_addr_o(spad_addr_o),
    .spad_rdata_i(spad_rdata_i),
    .spad_ready_i(spad_ready_i)
  );
endmodule
